"""PlatformIO pre-build hook: gzip data/ui/index.html into a C header.

The HTML is the source of truth. The header is generated and gitignored, so the
firmware is always built from the page currently on disk.
"""

Import("env")  # noqa: F821  - injected by PlatformIO

import gzip
import os

SOURCE = "data/ui/index.html"
TARGET = "src/config/internal/ui_index.h"
BYTES_PER_LINE = 16


def build_header(source_path, target_path):
    with open(source_path, "rb") as handle:
        raw = handle.read()

    # mtime=0 keeps the output byte-identical for identical input, so an
    # unchanged page never triggers a needless rebuild downstream.
    compressed = gzip.compress(raw, compresslevel=9, mtime=0)

    lines = [
        "// Generated by tools/embed_ui.py from data/ui/index.html.",
        "// Do not edit this file; edit the HTML instead.",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "inline constexpr size_t kUiIndexGzLength = %d;" % len(compressed),
        "",
        "inline constexpr uint8_t kUiIndexGz[] = {",
    ]
    for offset in range(0, len(compressed), BYTES_PER_LINE):
        chunk = compressed[offset:offset + BYTES_PER_LINE]
        lines.append("    " + " ".join("0x%02x," % byte for byte in chunk))
    lines.append("};")
    lines.append("")

    directory = os.path.dirname(target_path)
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(target_path, "w") as handle:
        handle.write("\n".join(lines))

    print("embed_ui: %s -> %s (%d -> %d bytes)"
          % (SOURCE, TARGET, len(raw), len(compressed)))


def main():
    project_dir = env["PROJECT_DIR"]  # noqa: F821
    source_path = os.path.join(project_dir, SOURCE)
    target_path = os.path.join(project_dir, TARGET)

    if not os.path.isfile(source_path):
        raise Exception("embed_ui: missing %s" % source_path)

    if (os.path.isfile(target_path)
            and os.path.getmtime(target_path) >= os.path.getmtime(source_path)):
        return

    build_header(source_path, target_path)


main()
